### ISSUE TITLE
Using Flotta to manage Raspberry Pi not working with Fedora IoT 35

### ISSUE THREAD

**Issue by dpshekhawat** [project-flotta/project-flotta.github.io#105]
I followed the steps of managing Raspberry Pi using Flotta on Fedora IoT 35 -

- while executing the uploaded script `install-agent-rpm-ostree.sh` on the device generated this error.

```
error: Failed to load /ostree/deploy/fedora-iot/deploy/0cbf945b7cd2538668fa45f0ddeb65cc71d337de54a3a37d47d923ba975f2ca6.0/etc/yum.repos.d/project-flotta.repo: 
Key file contains line “<!doctype html>” which is not a key-value pair, group, or comment
```

**Comment by pkliczewski** [comment]
This issue looks like temporary (potentially network issue) with fedora [copr](https://copr.fedorainfracloud.org/coprs/project-flotta/). Do you still see the issue?

**Comment by dpshekhawat** [comment]
right! could be a network issue. No, it's resolved now.
